name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_SPRING_SECURITY_USER_NAME: ${{ secrets.SPRING_SECURITY_USER_NAME }}
        envkey_SPRING_SECURITY_USER_PASSWORD: ${{ secrets.SPRING_SECURITY_USER_PASSWORD }}
        envkey_POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        file_name: .env

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    # is this really necessary ?
    - name: Grant execute permission for Maven wrapper
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw clean install

    # is this really necessary ?
    - name: Grant execute permission for Maven wrapper
      run: chmod +x mvnw

    - name: Run tests
      run: ./mvnw test

    - name: Generate coverage report
      run: mvn jacoco:report

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true